[build-system]
requires = ["setuptools>=68.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "studio-restore"
version = "3.0.0"
description = "Studio.Restore() — программа для восстановления студий в Scratch."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "PyQt6",
    "requests",
]
license = { file = "LICENSE" }
authors = [
    { name = "gervaty" },
    { name = "polzovatel_5555" },
    { name = "Grisshink"},
]

[tool.setuptools]
scripts = ["src/Studio-Restore.pyw"]
